version: "3.7"
services:
  app:
    build:
      args:
        user: ${DEV_NAME}
        uid: ${DEV_UID}
      context: ./
      dockerfile: Dockerfile
    image: telework-app-img
    container_name: telework-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - telework

  db:
    image: mysql:5.7
    container_name: telework-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - telework_db:/var/lib/mysql
    networks:
      - telework

  redis:
    image: redis:alpine
    networks:
      - telework
    container_name: telework-redis

  nginx:
    image: nginx:alpine
    container_name: telework-nginx
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - telework

volumes:
  telework_db:
networks:
  telework:
    driver: bridge
